name: Generate docs

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: v18.x
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install NPM packages
        working-directory: ./docs/scripts
        run: npm ci
      - name: Download LuaLS
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'luals/lua-language-server'
          version: 'tags/3.7.4'
          file: 'lua-language-server-3.7.4-linux-x64.tar.gz'
          target: './docs/scripts/temp/luals/luals.tar.gz'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract LuaLS
        working-directory: ./docs/scripts/temp/luals
        run: tar -xzf luals.tar.gz
      - name: Generate Lua docs
        working-directory: ./docs/scripts
        run: npx tsx generate.ts ./temp/luals/bin/lua-language-server
      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update Lua API docs"