name: Build

on:
  push:
    tags:
      - '*.*'
      - '*.*.*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: '2.8.5'
      - name: Cache XMake packages
        uses: actions/cache@v3
        with:
          key: build-${{ hashFiles('xmake.lua') }}
          path: |
            ~/AppData/Local/.xmake/packages
            ~/AppData/Local/.xmake/cache
      - name: Setup project
        run: xmake f -y -m release -a x86
      - name: Build test project
        run: xmake build -y test
      - name: Test
        env:
          TERM: xterm
        run: xmake run -y test --gtest_color=yes
      - name: Build
        run: ./build.bat ${{github.ref_name}}
      - id: create_release
        name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{github.ref_name}}
          name: ${{github.ref_name}}
          prerelease: ${{ contains(github.ref_name, 'beta') }}
          generate_release_notes: true
          files: |
            ./build/windows/x86/release/d3d8.dll
            ./build/windows/x86/release/d3d8.pdb
