name: Build

on:
  push:
    tags:
      - '*.*'
      - '*.*.*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      - name: Build
        run: ./build.bat ${{github.ref_name}}
      - name: Prepare SDK
        run: move src/scripting/env src/scripting/supermod-sdk
      - uses: vimtor/action-zip@v1
        name: Pack SDK
        with:
          files: src/scripting/supermod-sdk/
          dest: supermod-sdk.zip
      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{github.ref_name}}
          release_name: ${{github.ref_name}}
          draft: true
          prerelease: false
      - uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/windows/x86/release/dinput8.dll
          asset_name: dinput8.dll
          asset_content_type: application/octet-stream
      - uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./supermod-sdk.zip
          asset_name: supermod-sdk.zip
          asset_content_type: application/octet-stream
