name: Test

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup XMake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      - name: Get XMake dir
        id: xmake_dir
        run: |
          xmake l -c 'print("root=$(globaldir)")' >> "$GITHUB_OUTPUT"
      - name: Cache XMake packages
        uses: actions/cache@v3
        with:
          key: build-${{ hashFiles('xmake.lua') }}
          path: |
            ${{ steps.xmake_dir.outputs.root }}/packages
            ${{ steps.xmake_dir.outputs.root }}/cache
      - name: Test
        run: ./test.bat